---
- name: ensure curator dirs
  file:
    dest: '{{ item }}'
    state: directory
  with_items:
    - '{{ curator_dir }}'

- name: ensure curator config
  template:
    src: '{{ item }}.yml.j2'
    dest: '{{ curator_dir }}/{{ item }}.yml'
  with_items:
    - curator
    - action

- name: run curator container
  docker_container:
    state: started
    restart: yes
    recreate: yes
    name: '{{ curator_container_name }}'
    image: '{{ curator_image }}'
    restart_policy: 'no'
    pull: true
    links: '{{ curator_links }}'
    networks: '{{ curator_networks }}'
    volumes:
      - '{{ curator_dir }}/curator.yml:/etc/curator/curator.yml:ro'
      - '{{ curator_dir }}/action.yml:/etc/curator/action.yml:ro'
    command: '--config /etc/curator/curator.yml /etc/curator/action.yml'

- name: add curator job to crontab
  cron:
    name: execute curator
    minute: '0'
    hour: '*'
    job: docker start curator
